### PR TITLE
gitcoin passport styles

### PR DESCRIPTION
**Pull request by gerouvi**
New styles for gitcoin passport census

### CODE REVIEW

**Comment by jpaulet** [comment]
Requested changes:

- Add the border
- Prevent GPS input going over 100
- Set default GPS score to 15
- When switching to "AND" the text is displayed in 2 lines instead of 1.

**Review by jpaulet — CHANGES_REQUESTED** [review]
In Spanish and Catalan, after: "resistente a Sybil", add a mini-explanation, like:

- "resistente a Sybil (resistente a la falsificación de identidad)"
- "resistent a Sybil (resistent a la falsificació d'identitat)"

**Review by jpaulet — APPROVED** [review]
Checked the UI and looks good. Ready to merge

**Review by elboletaire — CHANGES_REQUESTED** [review]
Slight change on the NumberInput

**Review by elboletaire — APPROVED** [review]

**Pull request merged**
