### PR TITLE
2024-04 1st sprint staging upgrade

### PR DESCRIPTION
**Pull request by elboletaire**
Most significant changes in this staging upgrade:
- #555
- #570
- #572 
- #584 
- #596 
- #607
- #615 
- #617

### CODE REVIEW

**Comment by jpaulet** [comment]
**1 -** In the STG onvote app, the Gitcoin Passport image doesn't load: 
image

Replace with this image instead:
image

**2 -** Check this error in the voting page: 
image

**3 -** The first time everything went well, but the second attempt, gave me this error:
image
(maybe we should add a "Retry" button when this button happens).

**4 -** The `GPS-Based Voting Weight` shouldn't be checked by default. I believe that default behavior should be the "1" weight. 

**+** This issue should be addressed before merging it into LTS: https://github.com/vocdoni/ui-scaffold/issues/616

**Comment by jpaulet** [comment]
In the Voting page, we should find a better way to display the conditions to vote in the GPS census, and try to reproduce it in a similar way than the "preview step", where you can find the selected stamps. 

**Census strategy:** 
_Gitcoin Passport Score_: Min. score 20

And if at least one stamp is selected:

_**Needed Stamps** (at least one of them/all of them)_: 
image

And show a list of icons with the name as a tooltip.

**Comment by selankon** [comment]
> **1 -** In the STG onvote app, the Gitcoin Passport image doesn't load:

The returned iconURI is wrong: `​iconURI: "https://ipfs.io/ipfs/bafybeiehrtssiqivcxq3af2fnyeys5n75cka62irkks66ueq2hgllq43ji/no-image.svg"` @lucasmenendez could you update the backend?

**Comment by selankon** [comment]
> 2 - Check this error in the voting page: 

3a9d002

**Comment by selankon** [comment]
> In the Voting page, we should find a better way to display the conditions to vote in the GPS census, and try to reproduce it in a similar way than the "preview step", where you can find the selected stamps.
> 
> **Census strategy:** _Gitcoin Passport Score_: Min. score 20
> 
> And if at least one stamp is selected:
> 
> _**Needed Stamps** (at least one of them/all of them)_: image
> 
> And show a list of icons with the name as a tooltip.

We are talking on discord about how to fix this

**Pull request merged**
