### PR TITLE
Implement share modal

### PR DESCRIPTION
**Pull request by selankon**
Fixes https://github.com/vocdoni/interoperability/issues/148

### CODE REVIEW

**Comment by jpaulet** [comment]
1 - When I hover over any icon, it displays: "Share on [object Object]."
2 - Make the font size of the input smaller (like 12px) so that the URL looks clearer. Also, place the "Copy" button below to avoid cutting the input off.
3 - Make the share icon more visible (as the design provided)

image
image

**Review by jpaulet — APPROVED** [review]

**Comment by selankon** [comment]
> 1 - When I hover over any icon, it displays: "Share on [object Object]."
> 2 - Make the font size of the input smaller (like 12px) so that the URL looks clearer. Also, place the "Copy" button below to avoid cutting the input off.
> 3 - Make the share icon more visible (as the design provided)

This changes are already fixed and the pr is approved by Aulet

**Review by elboletaire — CHANGES_REQUESTED** [review]
This is what I see on the deployed instances:
imatge
imatge

**Comment by selankon** [comment]
> This is what I see on the deployed instances:

Well this is so strange because is not happening to me on my FF....  Maybe is the FF cache related? Which is the problem, the icons doesn't load or have a bad style?

image

**Comment by elboletaire** [comment]
There's a style hiding them:

imatge

**Comment by elboletaire** [comment]
It was adblocker doing its magic, I love it
imatge

**Review by elboletaire — APPROVED** [review]

**Pull request merged**
